
export const ADD_USERCITY = 'ADD_USERCITY';
export const GET_AUTOCOMPLETEDATA = 'GET_AUTOCOMPLETEDATA';
export const CHOSEN_CITY = 'CHOSEN_CITY';
export const GET_LOCATIONDATA = 'GET_LOCATIONDATA';
export const REMOVE_CARD = 'REMOVE_CARD';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_AUTOCOMPLETEDATA = 'CLEAR_AUTOCOMPLETEDATA';
